### ISSUE TITLE
Heatmap for paths with variable urls not working

### ISSUE THREAD

**Issue by jafuentest** [Qbatch/heatmap-rails#6]
URLs like `/user/:id/` where :id is any integer only show the clicks for that user and not all users in general.
Anyone know a quick workaround or is this feature not supported?

**Comment by hassanakram** [comment]
@jafuentest We are going to release next version in couple of days, which should support this.

**Comment by hassanakram** [comment]
@jafuentest The newer version(0.2.0) should support dynamic URLs as well.
